name: Get Delta and Deploy

on:
  workflow_dispatch:
    inputs:
      source-repo-url:
        description: 'URL of the source repository to clone'
        required: true
      source-branch-name:
        description: 'Branch in the source repository'
        required: true
      target-repo-url:
        description: 'URL of the target repository to clone for deployment'
        required: true
      target-branch-name:
        description: 'Branch in the target repository for deployment'
        required: true

jobs:
  get_delta_and_deploy:
    name: Get Delta and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
                 
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install SFDX-CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
          mkdir ~/sfdx && ls -la
          tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
          echo "$HOME/sfdx/bin" >> $GITHUB_PATH
          echo The PATH is $GITHUB_PATH
          ~/sfdx/bin/sfdx version

      # - name: Read Json file to get the version
      #   run: |
      #     versionNumber=$(jq -r '.status' validate.json)
      #     echo $versionNumber
      #     echo "SfdxValidateStatusCode=$versionNumber" >> $GITHUB_ENV
      #     if [[ "$statusCode" == "0" ]]; then
      #       resultId=$(jq -r '.result.id' validate.json)       
      #       echo "resultID=$resultId" >> $GITHUB_ENV
      #     fi
          
      - name: Clone Source Repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.source-repo-url }}
          ref: ${{ github.event.inputs.source-branch-name }}
          token: ${{ secrets.V_METADATA_SEC }}
          path: source-repo
      
      # - name: Extract files from source repo
        
      - name: Directory list
        run: ls -la
      - name: Authenticate with Salesforce
        run: |
          sfdx auth:jwt:grant --username vishklearning-kkyx@force.com -f ./assests/server.key -i 3MVG9pRzvMkjMb6lQqNGD2Din84lDhzACIb8UOjKFaDT4GcRVUFVNHq79MC5AsrZx0tFPcQ2BWrmcua0RK0O0 -r https://efficiency-ability-9696.my.salesforce.com
      
      - name: Deploy Global Core to Target Repository
        run: |
          cd source-repo
          sf project deploy start --target-org vishklearning-kkyx@force.com --source-dir "force-app" --api-version ${{secrets.API_VERSION}} --wait 90 --json > deploy.json

       # Upload the output of force:sorce:deploy cmd in json file
      - name: Artifact Upload - ./deploy.json
        uses: actions/upload-artifact@v3
        with:
          name: deploy.json
          path: ./deploy.json
          retention-days: 15
      
      # - name: Get Delta from Source Repository
      #   run: |
      #     cd source-repo
      #     delta=$(sfdx force:source:status -u <alias> --json | jq '.result | map(select(.state == "Changed")) | map(.fullName) | join(",")')

      # - name: Clone Target Repository for Deployment
      #   uses: actions/checkout@v2
      #   with:
      #     repository: ${{ github.event.inputs.target-repo-url }}
      #     ref: ${{ github.event.inputs.target-branch-name }}
      #     token: ${{ secrets.V_METADATA_SEC }}
      #     path: target-repo
      # - name: Deploy Delta to Target Repository
      #   run: |
      #     cd target-repo
      #     sf project deploy start --target-org vishklearning-kkyx@force.com -p $delta --api-version ${{secrets.API_VERSION}} --wait 90 --json > deploy.json
      #     # sfdx force:source:deploy -p $delta -u vishklearning-kkyx@force.com --wait 10 --json
