name: Clone Another Repo
on: workflow_dispatch
jobs:
  clone-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Clone supercharge website repository
        uses: actions/checkout@v2

      # This part here is cloning a second repository
      # While cloning the repository:
      #   - it clones the repo into the given `path`
      #   - it checks out the branch defined at `ref`
      - name: Clone supercharge docs repository
        uses: actions/checkout@v2
        with:
          repository: vishklearning/SalesforceDemo
          path: SalesforceDemo/lwc/helloSetup/
          ref: SalesforceDemo
